### ISSUE TITLE
Difference between this and PHPUnit Enhancements?

### ISSUE THREAD

**Issue by tyteen4a03** [dimabdc/idea-php-phpunit-plugin#2]
PHPUnit Enhancements was updated about a week ago and finally supports PHPStorm 2020.2. Is there a need to keep using this plugin or does this plugin have fixes Enhancement doesn't have?

**Comment by dimabdc** [comment]
This plugin has its own development path.
At the moment, the main difference is the support for correct line termination and annotations for the onlyMethods and addMethods methods.
